#!/usr/bin/env node
// grafana-shots.e2e.mjs — end-to-end test for scripts/grafana-shots.mjs.
//
// Drives the real pipeline against the live local Grafana for a 2-dashboard subset
// (ONLY=…) into a TEMP README copy, then asserts: the dashboard PNGs were written and
// are non-blank (>20 KB), and the README gallery markers were populated with <img refs.
// Skips (does not fail) when Grafana/Playwright aren't available, so it's CI-safe.
//
// Run: PW_PATH="$(npm root -g)/playwright" node --test test/grafana-shots.e2e.mjs
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const GRAFANA = (process.env.GRAFANA_URL || "http://127.0.0.1:3300").replace(/\/$/, "");
const AUTH = process.env.GRAFANA_AUTH || "admin:admin";
const PW = process.env.PW_PATH || `${execFileSync("npm", ["root", "-g"]).toString().trim()}/playwright`;
const SUBSET = ["lrn-exec", "ai-agents"]; // two representative dashboards (exec + live agents)

async function grafanaUp() {
  try { const r = await fetch(`${GRAFANA}/api/health`, { signal: AbortSignal.timeout(2500) }); return r.ok; }
  catch { return false; }
}

test("grafana-shots: screenshots all dashboards and injects a README gallery", async (t) => {
  if (!(await grafanaUp())) return t.skip(`Grafana not reachable at ${GRAFANA}`);
  if (!fs.existsSync(PW)) return t.skip(`Playwright not found at ${PW}`);

  // isolated workspace: temp README + temp shot dir so the real files are untouched
  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "lrn-shots-e2e-"));
  const readme = path.join(tmp, "README.md");
  fs.writeFileSync(readme, [
    "# test", "",
    "<!-- DASHBOARD-SHOTS:START (generated by scripts/grafana-shots.mjs — do not edit by hand) -->",
    "placeholder",
    "<!-- DASHBOARD-SHOTS:END -->", "",
    "## Setup", "",
  ].join("\n"));
  const shotDir = path.join(tmp, "shots");

  execFileSync("node", [path.join(ROOT, "scripts", "grafana-shots.mjs")], {
    stdio: "inherit",
    env: { ...process.env, PW_PATH: PW, GRAFANA_URL: GRAFANA, GRAFANA_AUTH: AUTH,
           README: readme, SHOT_DIR: shotDir, ONLY: SUBSET.join(","), SETTLE_MS: "9000" },
    timeout: 120000,
  });

  // 1) every requested dashboard produced a non-blank PNG
  for (const uid of SUBSET) {
    const f = path.join(shotDir, `${uid}.png`);
    assert.ok(fs.existsSync(f), `missing screenshot ${uid}.png`);
    const kb = fs.statSync(f).size / 1024;
    assert.ok(kb > 20, `${uid}.png looks blank (${kb.toFixed(0)} KB ≤ 20 KB)`);
    // PNG magic bytes
    const head = fs.readFileSync(f).subarray(0, 8);
    assert.deepEqual([...head], [0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a], `${uid}.png not a valid PNG`);
  }

  // 2) README gallery markers populated and reference each image
  const md = fs.readFileSync(readme, "utf8");
  assert.ok(md.includes("DASHBOARD-SHOTS:START") && md.includes("DASHBOARD-SHOTS:END"), "markers gone");
  assert.ok(!md.includes("placeholder"), "placeholder not replaced");
  for (const uid of SUBSET) assert.match(md, new RegExp(`!\\[[^\\]]*\\]\\([^)]*${uid}\\.png\\)`), `gallery missing img for ${uid}`);

  fs.rmSync(tmp, { recursive: true, force: true });
});
