#!/usr/bin/env node
// grafana-shots.mjs — screenshot EVERY Grafana dashboard and embed a gallery into README.md.
//
// Discovers all dashboards via the Grafana API, computes each dashboard's true pixel height
// from its panel grid (so tall dashboards are captured whole, not cropped), renders each in
// kiosk mode with a viewport-only capture (fullPage races Grafana's scene relayout and blanks
// panels), writes proof/grafana/<uid>.png, then rewrites the gallery between README markers.
//
// ENV: GRAFANA_URL (http://127.0.0.1:3300) · GRAFANA_AUTH (admin:admin) · PW_PATH (playwright)
//      README (README.md) · SHOT_DIR (proof/grafana) · RANGE (now-3h) · REBUILD (0|1)
//      SETTLE_MS (9000) · ONLY (comma-sep uid filter)
import { createRequire } from "node:module";
import { execSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const BASE = (process.env.GRAFANA_URL || "http://127.0.0.1:3300").replace(/\/$/, "");
const AUTH = process.env.GRAFANA_AUTH || "admin:admin";
const [USER, PASS] = AUTH.split(":");
const README = path.resolve(ROOT, process.env.README || "README.md");
const SHOT_DIR = path.resolve(ROOT, process.env.SHOT_DIR || "proof/grafana");
const REL_DIR = path.relative(path.dirname(README), SHOT_DIR) || ".";
const RANGE = process.env.RANGE || "now-3h";
const SETTLE_MS = Number(process.env.SETTLE_MS || 9000);
const ONLY = (process.env.ONLY || "").split(",").map((s) => s.trim()).filter(Boolean);
const MARK_START = "<!-- DASHBOARD-SHOTS:START (generated by scripts/grafana-shots.mjs — do not edit by hand) -->";
const MARK_END = "<!-- DASHBOARD-SHOTS:END -->";
const GRID_CELL_PX = 30; // Grafana grid row height
const authHeader = { Authorization: "Basic " + Buffer.from(AUTH).toString("base64") };

async function api(p) {
  const res = await fetch(`${BASE}${p}`, { headers: authHeader });
  if (!res.ok) throw new Error(`GET ${p} → HTTP ${res.status}`);
  return res.json();
}

// optional: regenerate all dashboards first so the gallery reflects the latest build scripts
if (process.env.REBUILD === "1") {
  for (const b of ["grafana-build-all", "grafana-build-aw", "grafana-build-whoop-lab", "grafana-build-weekly", "grafana-build-agents", "grafana-build-fusion", "grafana-build-big-display", "grafana-build-index"]) {
    try { execSync(`GRAFANA_URL=${BASE} GRAFANA_DS_UID=${process.env.GRAFANA_DS_UID || "prometheus"} node ${path.join(ROOT, "scripts", b + ".mjs")}`, { stdio: "inherit" }); }
    catch { console.error(`! rebuild ${b} failed (continuing)`); }
  }
}

// 1) discover dashboards, sort by the numeric prefix in the title ("0 · …", "10 · …")
let dashes = await api("/api/search?type=dash-db");
if (ONLY.length) dashes = dashes.filter((d) => ONLY.includes(d.uid));
const numOf = (t) => { const m = String(t).match(/^\s*(\d+)/); return m ? Number(m[1]) : 999; };
dashes.sort((a, b) => numOf(a.title) - numOf(b.title) || a.title.localeCompare(b.title));
if (!dashes.length) { console.error("no dashboards found — is Grafana up and provisioned?"); process.exit(1); }

// 2) render
fs.mkdirSync(SHOT_DIR, { recursive: true });
const { chromium } = require(process.env.PW_PATH || "playwright");
const browser = await chromium.launch({ channel: "chrome", args: ["--no-sandbox"] });
const results = [];
for (const d of dashes) {
  // compute true height from the panel grid so nothing is cropped or lazy-unloaded
  let maxRow = 24;
  try {
    const full = await api(`/api/dashboards/uid/${d.uid}`);
    const panels = full.dashboard.panels || [];
    maxRow = panels.reduce((m, p) => Math.max(m, (p.gridPos?.y || 0) + (p.gridPos?.h || 8)), 8);
  } catch { /* fall back to default height */ }
  const height = Math.min(Math.max(maxRow * GRID_CELL_PX + 90, 620), 5400);
  const dsf = height > 3000 ? 1 : 2; // keep very tall dashboards a sane file size
  const ctx = await browser.newContext({
    httpCredentials: USER ? { username: USER, password: PASS } : undefined, // never put creds in the URL (breaks Grafana's own fetch)
    viewport: { width: 1500, height }, deviceScaleFactor: dsf, ignoreHTTPSErrors: true,
  });
  const page = await ctx.newPage();
  const url = `${BASE}/d/${d.uid}/d?kiosk&from=${RANGE}&to=now`;
  await page.goto(url, { waitUntil: "load", timeout: 45000 }).catch((e) => console.error(`  goto ${d.uid}: ${e.name}`));
  await page.waitForTimeout(SETTLE_MS); // let panels + countdowns settle
  const out = path.join(SHOT_DIR, `${d.uid}.png`);
  await page.screenshot({ path: out, fullPage: false }); // viewport-only: avoids scene-relayout blanking
  await ctx.close();
  const bytes = fs.statSync(out).size;
  results.push({ uid: d.uid, title: d.title, file: out, rel: `${REL_DIR}/${d.uid}.png`, bytes });
  console.log(`${bytes > 20000 ? "✅" : "⚠️ "} ${d.title.padEnd(42)} ${(bytes / 1024).toFixed(0)} KB  ${out}`);
}
await browser.close();

// 3) build the markdown gallery and inject it between the README markers.
// Stacked full-width images (each links to the full-res PNG) — reads cleanly on a phone,
// where a multi-column table would shrink each dashboard to an unreadable thumbnail.
const blocks = results.map((r) => {
  const alt = r.title.replace(/\|/g, "·").replace(/[[\]]/g, "");
  return `#### ${r.title}\n\n[![${alt}](${r.rel})](${r.rel})`;
}).join("\n\n");
const gallery = [
  MARK_START,
  `_${results.length} Dashboards · auto-captured from \`${BASE}\` · regenerate with \`node scripts/grafana-shots.mjs\`. Tap any image for full resolution._`,
  "",
  blocks,
  "",
  MARK_END,
].join("\n");

let md = fs.readFileSync(README, "utf8");
if (md.includes(MARK_START) && md.includes(MARK_END)) {
  md = md.slice(0, md.indexOf(MARK_START)) + gallery + md.slice(md.indexOf(MARK_END) + MARK_END.length);
} else {
  // first run: append a new section
  md = md.replace(/\n## Setup/, `\n## Dashboard gallery\n\n${gallery}\n\n## Setup`);
  if (!md.includes(MARK_START)) md += `\n\n## Dashboard gallery\n\n${gallery}\n`;
}
fs.writeFileSync(README, md);
const weak = results.filter((r) => r.bytes <= 20000);
console.log(`\n${results.length} dashboards → ${path.relative(ROOT, README)} (gallery injected)${weak.length ? `  ·  ⚠️ ${weak.length} look blank: ${weak.map((w) => w.uid).join(", ")}` : ""}`);
